import type { Metadata } from "next";
import Breadcrumbs from "@/components/breadcrumbs";
import PageIcon from "@/components/page-icon";

export const metadata: Metadata = { title: "Kebijakan Privasi | Skillbridge AI", description: "Informasi data, pemrosesan AI, penyimpanan, dan hak pengguna Skillbridge AI." };

export default function PrivacyPage() {
  return <main id="main"><Breadcrumbs current="Kebijakan privasi"/><header className="support-head"><div><p className="eyebrow">Privasi</p><h1>Data seperlunya. Kontrol tetap milik Anda.</h1><p className="lede">Ringkasan pemrosesan data pada prototipe Skillbridge AI.</p></div><PageIcon type="lock"/></header><article className="policy panel"><section><h2>Data yang diproses</h2><p>Email dipakai untuk autentikasi. Bukti dapat berupa URL GitHub publik, gambar karya dan deskripsi proses, atau laporan PDF. Sistem menyimpan hasil, alasan, referensi bukti, versi rubrik, dan metadata teknis yang diperlukan.</p></section><section><h2>Pemrosesan AI</h2><p>Bukti hanya dikirim ke Groq setelah Anda memberi persetujuan. Nama dan email tidak sengaja dimasukkan ke prompt penilaian. Jangan mengunggah password, API key, private key, atau data pribadi pihak lain.</p></section><section><h2>Penyimpanan dan keamanan</h2><p>File disimpan pada bucket Supabase privat. Akses hasil diperiksa berdasarkan akun pemilik. Sistem menerapkan validasi file, pembatasan penggunaan, dan cache privat.</p></section><section><h2>Penghapusan</h2><p>Anda dapat menghapus assessment dari halaman hasil. Sistem memproses penghapusan record, skor turunan, dan file terkait. Kegagalan penghapusan file dicatat untuk diproses ulang.</p></section><section><h2>Batas prototipe</h2><p>Skillbridge bukan layanan verifikasi identitas atau kepemilikan karya. Jangan gunakan hasil sebagai satu-satunya dasar keputusan pendidikan, rekrutmen, atau pekerjaan.</p></section><section><h2>Pembaruan</h2><p>Kebijakan ini berlaku untuk versi prototipe per 30 Agustus 2026 dan dapat diperbarui jika provider, jenis data, atau alur produk berubah.</p></section></article></main>;
}
