"use client";
import { useEffect, useState } from "react";
import { useAssessments } from "@/lib/assessment-client";
import { authHeaders } from "@/lib/auth-client";
import { responseData } from "@/lib/http-client";
type Message = { role: "user" | "assistant"; content: string };
export default function InterviewView({ id }: { id: string }) { const { items, loading: loadingAssessment } = useAssessments(id); const assessment = items[0]; const [messages, setMessages] = useState<Message[]>([]); const [answer, setAnswer] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [sessionDone, setSessionDone] = useState(false); const [initialLoading, setInitialLoading] = useState(true);
  useEffect(() => { if (!id) return; authHeaders().then((h) => fetch(`/api/interview?assessmentId=${encodeURIComponent(id)}`, { headers: h })).then(async (r) => { const d = await responseData(r) as { messages?: Message[]; status?: string }; if (r.ok && d.messages?.length) { setMessages(d.messages); if (d.status === "completed") setSessionDone(true); } }).catch(() => {}).finally(() => setInitialLoading(false)); }, [id]);
  async function ask(userAnswer?: string) { if (!assessment) return; setLoading(true); setError(""); try { const body: Record<string, string> = { assessmentId: id }; if (userAnswer) body.answer = userAnswer; const response = await fetch("/api/interview", { method: "POST", headers: await authHeaders(), body: JSON.stringify(body) }); const data = await responseData(response) as { error?: string; message?: string; answerCount?: number }; if (!response.ok) throw new Error(String(data.error)); const newMessages: Message[] = [...messages]; if (userAnswer) newMessages.push({ role: "user", content: userAnswer }); newMessages.push({ role: "assistant", content: String(data.message) }); setMessages(newMessages); if ((data.answerCount ?? 0) >= 5) setSessionDone(true); } catch (cause) { setError(cause instanceof Error ? cause.message : "Wawancara belum dapat diproses."); } finally { setLoading(false); } }
  function submit(event: React.FormEvent) { event.preventDefault(); if (!answer.trim() || sessionDone) return; const text = answer.trim(); setAnswer(""); ask(text); }
  const count = messages.filter(({ role }) => role === "user").length;
  if (loadingAssessment || initialLoading) return <header className="page-head"><p>Memuat penilaian...</p></header>; if (!assessment) return <header className="page-head"><h1>Penilaian tidak ditemukan.</h1></header>;
  return <><header className="page-head"><p className="eyebrow">Wawancara · {count}/5 jawaban</p><h1>Latihan dari gap nyata.</h1><p className="lede">Feedback wawancara terpisah dari skor bukti kerja.</p></header><section className="form-shell"><div className="panel">{error && <div className="alert" role="alert">{error}</div>}{!messages.length && <button className="button" onClick={() => ask()} disabled={loading}>{loading ? "Menyiapkan..." : "Mulai pertanyaan pertama"}</button>}{messages.map((message, index) => <article className="criterion" key={index}><strong>{message.role === "assistant" ? "Pewawancara" : "Anda"}</strong><p>{message.content}</p></article>)}{messages.length > 0 && !sessionDone && <form onSubmit={submit}><div className="field"><label htmlFor="answer">Jawaban Anda</label><textarea id="answer" rows={5} value={answer} onChange={(event) => setAnswer(event.target.value)} required maxLength={3000}/></div><button className="button" disabled={loading}>{loading ? "Menilai jawaban..." : "Kirim jawaban"}</button></form>}{sessionDone && <p className="alert">Sesi lima jawaban selesai. Gunakan feedback terakhir sebagai latihan berikutnya.</p>}</div><aside className="panel"><p className="eyebrow">Fokus sesi</p>{assessment.gaps.slice(0, 2).map((gap) => <p className="chip" key={gap}>{gap}</p>)}</aside></section></>;
}
