"use client";
import { useState } from "react";
import { useAssessments } from "@/lib/assessment-client";
import { authHeaders } from "@/lib/auth-client";
type Message = { role: "user" | "assistant"; content: string };
export default function InterviewView({ id }: { id: string }) { const { items, loading: loadingAssessment } = useAssessments(id); const assessment = items[0]; const [messages, setMessages] = useState<Message[]>([]); const [answer, setAnswer] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function ask(nextMessages = messages) { if (!assessment) return; setLoading(true); setError(""); try { const response = await fetch("/api/interview", { method: "POST", headers: await authHeaders(), body: JSON.stringify({ assessmentId: id, answers: nextMessages.filter(({ role }) => role === "user").map(({ content }) => content) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setMessages([...nextMessages, { role: "assistant", content: data.message }]); } catch (cause) { setError(cause instanceof Error ? cause.message : "Wawancara belum dapat diproses."); } finally { setLoading(false); } }
  function submit(event: React.FormEvent) { event.preventDefault(); if (!answer.trim() || messages.filter(({ role }) => role === "user").length >= 5) return; const next: Message[] = [...messages, { role: "user", content: answer.trim() }]; setMessages(next); setAnswer(""); ask(next); }
  if (loadingAssessment) return <header className="page-head"><p>Memuat penilaian...</p></header>; if (!assessment) return <header className="page-head"><h1>Penilaian tidak ditemukan.</h1></header>; const count = messages.filter(({ role }) => role === "user").length;
  return <><header className="page-head"><p className="eyebrow">Wawancara · {count}/5 jawaban</p><h1>Latihan dari gap nyata.</h1><p className="lede">Feedback wawancara terpisah dari skor bukti kerja.</p></header><section className="form-shell"><div className="panel">{error && <div className="alert" role="alert">{error}</div>}{!messages.length && <button className="button" onClick={() => ask()} disabled={loading}>{loading ? "Menyiapkan..." : "Mulai pertanyaan pertama"}</button>}{messages.map((message, index) => <article className="criterion" key={index}><strong>{message.role === "assistant" ? "Pewawancara" : "Anda"}</strong><p>{message.content}</p></article>)}{messages.length > 0 && count < 5 && <form onSubmit={submit}><div className="field"><label htmlFor="answer">Jawaban Anda</label><textarea id="answer" rows={5} value={answer} onChange={(event) => setAnswer(event.target.value)} required maxLength={3000}/></div><button className="button" disabled={loading}>{loading ? "Menilai jawaban..." : "Kirim jawaban"}</button></form>}{count >= 5 && <p className="alert">Sesi lima jawaban selesai. Gunakan feedback terakhir sebagai latihan berikutnya.</p>}</div><aside className="panel"><p className="eyebrow">Fokus sesi</p>{assessment.gaps.slice(0, 2).map((gap) => <p className="chip" key={gap}>{gap}</p>)}</aside></section></>;
}
